
cc_test(
    name = "CppUnitXLite_test",
    srcs = ["CppUnitXLiteTests.cpp", "CppUnitXLiteTests.hpp"],
    deps = ["//:CppUnitXLite"]
)


cc_test(
    name = "CppUnitXLiteNoMacro_test",
    srcs = ["NoMacroTests.cpp", "CppUnitXLiteTests.hpp"],
    deps = ["//:CppUnitXLite"]
)
