# SlickEdit generated file.  Do not edit this file except in designated areas.

# Make command to use for dependencies
MAKE=make
RM=rm
MKDIR=mkdir

# -----Begin user-editable area-----

# -----End user-editable area-----

# If no configuration is specified, "Debug" will be used
ifndef CFG
CFG=Debug
endif

#
# Configuration: Debug
#
ifeq "$(CFG)" "Debug"
OUTDIR=Debug
OUTFILE=$(OUTDIR)/CppUnitXLiteTests
CFG_INC=-I../.. 
CFG_LIB=
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/CppUnitXLiteTests.o $(OUTDIR)/NoMacroTests.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/CppUnitXLiteTests.o $(OUTDIR)/NoMacroTests.o 

COMPILE=clang++ -c   -g -std=c++11 -o "$(OUTDIR)/$(*F).o" $(CFG_INC) $<
LINK=clang++  -g -o "$(OUTFILE)" $(ALL_OBJ)

# Pattern rules
$(OUTDIR)/%.o : %.cpp
	$(COMPILE)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif

#
# Configuration: Release
#
ifeq "$(CFG)" "Release"
OUTDIR=Release
OUTFILE=$(OUTDIR)/CppUnitXLiteTests
CFG_INC=-I../.. 
CFG_LIB=
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/CppUnitXLiteTests.o $(OUTDIR)/NoMacroTests.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/CppUnitXLiteTests.o $(OUTDIR)/NoMacroTests.o 

COMPILE=clang++ -c   -std=c++11 -o "$(OUTDIR)/$(*F).o" $(CFG_INC) $<
LINK=clang++  -o "$(OUTFILE)" $(ALL_OBJ)

# Pattern rules
$(OUTDIR)/%.o : %.cpp
	$(COMPILE)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif
